aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00001.jpg"}}' --external-image-id File00001.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00002.jpg"}}' --external-image-id File00002.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00003.jpg"}}' --external-image-id File00003.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00004.jpg"}}' --external-image-id File00004.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00005.jpg"}}' --external-image-id File00005.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00006.jpg"}}' --external-image-id File00006.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00007.jpg"}}' --external-image-id File00007.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00008.jpg"}}' --external-image-id File00008.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00009.jpg"}}' --external-image-id File00009.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00010.jpg"}}' --external-image-id File00010.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00011.jpg"}}' --external-image-id File00011.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00012.jpg"}}' --external-image-id File00012.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00013.jpg"}}' --external-image-id File00013.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00014.jpg"}}' --external-image-id File00014.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00016.jpg"}}' --external-image-id File00016.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00017.jpg"}}' --external-image-id File00017.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00018.jpg"}}' --external-image-id File00018.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00019.jpg"}}' --external-image-id File00019.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00020.jpg"}}' --external-image-id File00020.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00021.jpg"}}' --external-image-id File00021.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00022.jpg"}}' --external-image-id File00022.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00023.jpg"}}' --external-image-id File00023.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00024.jpg"}}' --external-image-id File00024.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00025.jpg"}}' --external-image-id File00025.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00026.jpg"}}' --external-image-id File00026.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00027.jpg"}}' --external-image-id File00027.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00029.jpg"}}' --external-image-id File00029.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00030.jpg"}}' --external-image-id File00030.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00031.jpg"}}' --external-image-id File00031.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00032.jpg"}}' --external-image-id File00032.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00033.jpg"}}' --external-image-id File00033.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00034.jpg"}}' --external-image-id File00034.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00035.jpg"}}' --external-image-id File00035.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00037.jpg"}}' --external-image-id File00037.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00038.jpg"}}' --external-image-id File00038.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00039.jpg"}}' --external-image-id File00039.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00040.jpg"}}' --external-image-id File00040.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00041.jpg"}}' --external-image-id File00041.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00042.jpg"}}' --external-image-id File00042.jpg
aws rekognition index-faces --collection-id faces-collection --image '{"S3Object":{"Bucket":"rekognize-faces","Name":"File00043.jpg"}}' --external-image-id File00043.jpg

